### ISSUE TITLE
Echappement ds mots clefs dans les facettes

### ISSUE THREAD

**Issue by EstelleChaix** [Bibliome/alvisir#10]
Via les facettes la requête  avec le label avec des mots tels que "and" (e.g: "milk and milk product") ne fonctionnent pas : on arrive sur l'URL
"milk and milk product"  http://bibliome.jouy.inra.fr/demo/food/alvisir/webapi/search?q=%22milk+and+milk+product%22

Par contre si on met  \and  c'est fonctionnel 
"milk \and milk product" : http://bibliome.jouy.inra.fr/demo/food/alvisir/webapi/search?q=%22milk+%5Cand+milk+product%22

**Comment by rbossy** [comment]
List of keywords to escape:
`or` `and` `not` `"` `[` `]`
