### ISSUE TITLE
More configurable UI

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisir#11]
* images
  - `alvis.png` (AlvisIR logo)
  - `background.jpg` `background-left.jpg` `background-right.jpg`
* ~~cheatsheet~~

**Comment by rbossy** [comment]
Solved for images in: c99e4bdc21100910530c831f322e6afc9758c1ff
Waiting for tests

**Comment by ldeleger** [comment]
Looks like it's working ok
