### ISSUE TITLE
Customizable cheatsheet

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisir#12]

**Comment by rbossy** [comment]
22df646f469d74c8b49b9b2af4f3e6f1892ee8c8

Custom cheat sheet contents can be specified through the `cheatsheet-html-path` display parameter.

The cheat sheet file must be an HTML file with a `div` root.

The default cheat sheet can be accessed at the URL: `/html/cheatsheet.html`.

The effective cheat sheet can be accessed at the URL: `/webapi/resources/html/cheatsheet.html`.

**Comment by ldeleger** [comment]
Tested on Microbes, works well
