### ISSUE TITLE
Phenotypes facet labels are idential to canonical value 

### ISSUE THREAD

**Issue by EstelleChaix** [Bibliome/alvisir#17]
Some facet values of Phenotypes part are paths 

Example for [{taxon}* livesin {habitat}*](http://bibliome.jouy.inra.fr/demo/food/alvisir/webapi/search?q=%28%7Btaxon%7D*+%7Elivesin+%7Bhabitat%7D*%29)

Facet's label | Canonical value | Total number of occurrences of the facet | Number of documents containing the facet
-- | -- | -- | --
pathogen | {phenotype}/moph:00000520/moph:00000521/moph:00000528/ | 551 | 290
{phenotype}/moph:00000520/moph:00001730/ec:0000208/ | {phenotype}/moph:00000520/moph:00001730/ec:0000208/ | 364 | 187
{phenotype}/moph:00000520/ec:0000210/ec:0000211/ | {phenotype}/moph:00000520/ec:0000210/ec:0000211/ | 331 | 153
{phenotype}/moph:00000520/moph:00001303/moph:00001308/ | {phenotype}/moph:00000520/moph:00001303/moph:00001308/ | 240 | 133
{phenotype}/moph:00000520/moph:00001303/moph:00001312/ | {phenotype}/moph:00000520/moph:00001303/moph:00001312/ | 281 | 105
{phenotype}/moph:00000520/moph:00001730/ec:0000209/ | {phenotype}/moph:00000520/moph:00001730/ec:0000209/ | 116 | 90
{phenotype}/moph:00000520/moph:00001313/moph:00001314/ | {phenotype}/moph:00000520/moph:00001313/moph:00001314/ | 88 | 51
{phenotype}/moph:00000520/moph:00001727/moph:00001728/ | {phenotype}/moph:00000520/moph:00001727/moph:00001728/ | 34 | 26
parasite | {phenotype}/moph:00000520/moph:00000521/moph:00001733/ | 47 | 24
{phenotype}/moph:00000520/moph:00000460/moph:00000448/ | {phenotype}/moph:00000520/moph:00000460/moph:00000448/ | 42 | 22
commensal | {phenotype}/moph:00000520/moph:00000521/moph:00000526/ | 11 | 9
microbial phenotype | {phenotype}/moph:00000520/ | 9 | 8
human pathogen | {phenotype}/moph:00000520/moph:00000521/moph:00000528/moph:00000530/moph:00000513/ | 8 | 7
{phenotype}/moph:00000520/moph:00001730/ec:0000207/ | {phenotype}/moph:00000520/moph:00001730/ec:0000207/ | 7 | 7
{phenotype}/moph:00000520/moph:00001303/moph:00001306/ | {phenotype}/moph:00000520/moph:00001303/moph:00001306/ | 6 | 5
human pathogen | {phenotype}/moph:00000520/moph:00000521/moph:00000524/moph:00000530/moph:00000513/ | 5 | 5
endophyte | {phenotype}/moph:00000520/moph:00000521/moph:00000525/moph:00000489/ | 11 | 5
{phenotype}/moph:00000520/moph:00001730/ec:0000206/ | {phenotype}/moph:00000520/moph:00001730/ec:0000206/ | 4 | 4
{phenotype}/moph:00000520/moph:00000479/moph:00000481/moph:00000482/ | {phenotype}/moph:00000520/moph:00000479/moph:00000481/moph:00000482/ | 6 | 4
{phenotype}/moph:00000520/ec:0000210/ec:0000211/ec:0000213/ | {phenotype}/moph:00000520/ec:0000210/ec:0000211/ec:0000213/ | 3 | 3
{phenotype}/moph:00000520/moph:00000462/moph:00001256/ | {phenotype}/moph:00000520/moph:00000462/moph:00001256/ | 4 | 3
 ...

**Comment by rbossy** [comment]
`{phenotype}/moph:00000520/moph:00001730/ec:0000208/`

looks like "something-positive". Make sure it is actually in the resource used in the expansion index.

**Comment by EstelleChaix** [comment]
Resources uploaded
