### ISSUE TITLE
Change relation query syntax

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisir#2]
1. `firmicutes ~LivesIn food`
That is the current situation. Pros: quicker implementation. Cons: nubs can't handle it.

2. `firmicutes <Lives In> food`
Pros: spaces in relation names. Cons: two chars.

3. `firmicutes LivesIn-> food`
4. `firmicutes ->LivesIn food`
Pros: arrow. Cons: two chars.

5. `firmicutes :LivesIn food`
Pros: one char. Cons: -.

6. `firmicutes relation:LivesIn food`
7. `firmicutes rel:LivesIn food`
Pros: looks like RDF. Cons: longish.

8. `firmicutes LivesIn food`
Pros: extra short. Cons: implementation may take longer.

**Comment by mandiayba** [comment]
8. me semble plus simple pour utilisateur s'il ne pose pas derrière un problème d’interprétation.

Sinon 5. me semble bien aussi.

**Comment by rbossy** [comment]
Solved in bd1028a

Waiting for test in production indexes to merge.

**Comment by rbossy** [comment]
67a14d9 accept legacy syntax

**Comment by saubin78** [comment]
S'il est encore temps, je confirme les difficultés à pratiquer la syntaxe actuelle d'Alvis IR.
Je suis du même avis que Ba, 8 si possible, sinon 5.
Ce serait possible aussi de changer le fonctionnement de la recherche "vide" dans le cas où je veux toute la base? L'étoile n'est pas intuitive (et pourtant je cause bien regexp). Peut-on simplement autoriser de laisser la boîte vide et de cliquer sur Search

**Comment by rbossy** [comment]
La solution 8 est implémentée.

J'ai demandé son déploiement sur l'instance de test sur migale. Louise testera, et si ça marche, on reportera sur les autres instances visibles.

L'ancienne syntaxe restera valide.

**Comment by rbossy** [comment]
Merged in 4a730bf38c9190c4fb7ea4dfcd6b07de4c576378
