### ISSUE TITLE
MW Expansion without double quotes

### ISSUE THREAD

**Issue by rbossy** [Bibliome/alvisir#3]
Expand MW synonyms across term conjunctions, and use quotes to inhibit expansion.

## Current behavior

`"food for humans"` expands to `OBT:000035/food for human`

`food for humans` expands to `OBT:000003/food` `OBT:001804/human`, raw search for the term *for*

## New behaviour

`"food for humans"` does not expand, raw search for the sequence of terms *food*, *for*, and *human*.

`food for humans` expands to `OBT:000035/food for human`

`food for "humans"` expands to `OBT:000003/food`, raw search for terms *for* and *human*

`"food" for "humans"` does not expand, raw search for terms *food*, *for*, and *human*

**Comment by rbossy** [comment]
`food for humans` expands to `OBT:000035/food for human`

but would we also include `OBT:000003/food` and `OBT:001804/human` ?

I say NO.

**Comment by rbossy** [comment]
2aaa6664c9882ad7fc49f18cecc58e90e729a084

In the last version, it is possible to test the alternate supposedly better query syntax:

```xml
<alvisir-search
     index="..."
     expander-index="..."
     default-field="..."

     query-expansion="advanced">
```

Streaks of unquoted terms will be searched for expansions, including MW expansions. Quoted terms and phrases will be searched as-is (raw search, no expansion).

@ldeleger, @echaix, please test...

**Comment by ldeleger** [comment]
Tested on Microbes, looks good
