### ISSUE TITLE
Install fail

### ISSUE THREAD

**Issue by jibe-b** [Bibliome/alvisir#7]
## Steps to reproduce

`mvn clean package`

## Observed behaviour 

> Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.5.1:compile (default-compile) on project alvisir-core: Fatal error compiling: tools.jar not found: /usr/lib/jvm/java-8-openjdk-amd64/jre/../lib/tools.jar

**Comment by rbossy** [comment]
Quel est le résultat des commandes suivantes?

`hostname`

`echo $JAVA_HOME`

`which mvn`

`echo $M2_HOME`

**Comment by jibe-b** [comment]
Le Java Runtime Environment (JRE) était installé et non pas le Java Development Kit (JDK).

JAVA_HOME et M2_HOME sont paramétrées à l'installation du JDK
