### ISSUE TITLE
Chemins relatifs non possibles 

### ISSUE THREAD

**Issue by EstelleChaix** [Bibliome/alvisir#9]
**Dans search.xml les chemins :** 

```
<alvisir-search
    index="/toto/.../index"
    expander-index="/toto/.../expander"
    >
```

**Dans UIConfig.xml** 

 ` <alvisir-search filepath="/toto/.../search.xml" />`

**Comment by rbossy** [comment]
Done in e6c6af78c7193201cb4bf472978b8aa229d7d052.

## UIConfig.xml

* paths are relative to the directory containing the `UIConfig.xml` file
* alllows relative paths for the following properties:
  - `alvisir-search`
  - `alternate-stylesheet`
  - `extra-css`
  - `logo-png-path`
  - `background-jpg-path`
  - `background-left-jpg-path`
  - `background-right-jpg-path`
  - `ontology`

## search.xml

* paths are relative to the directory containing the `search.xml` file
* alllows relative paths for the following properties:
  - `index`
  - `expander-index`

**Comment by ldeleger** [comment]
Tested on Microbes, works well
